# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('link', models.TextField()),
                ('size', models.BigIntegerField()),
                ('uploaded', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('access_token', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.DeleteModel(
            name='DropboxYouTube',
        ),
        migrations.AddField(
            model_name='dropboxfiles',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.YoutubeToken'),
        ),
    ]
