# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20160405_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubetoken',
            name='refresh_token',
            field=models.TextField(default='None'),
        ),
    ]
